Migrate ner-tagger
Inist-CNRS/web-services pull request #102
Opened 2024-06-21 11:24 UTC by AlasDiablo

2024-06-21 12:58 UTC, parmentf requested changes

2024-06-21 12:58 UTC, parmentf commented on services/ner-tagger/Dockerfile
> +# Get all web services dvc files
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** ‏
```suggestion
# Get all web service's dvc files
```

2024-06-21 12:58 UTC, parmentf commented on services/ner-tagger/Dockerfile
> +# Build and install web services dependcies en files
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** ‏
```suggestion
# Build and install web services dependencies files
```

2024-06-21 12:58 UTC, parmentf commented on services/ner-tagger/README.md
> +# ws-ner-tagger@0.0.0
<!-- TODO's are small, trivial, but necessary changes. Distinguishing todo comments from issues: or suggestions: helps direct the reader's attention to comments requiring more involvement.  -->
**todo:** ‏Let's use 1.0.6 as a base
```suggestion
# ws-ner-tagger@1.0.6
```

2024-06-21 12:58 UTC, parmentf commented on services/ner-tagger/README.md
> +Détéction d'entités nommées dans des textes anglais
<!-- Suggestions propose improvements to the current subject. It's important to be explicit and clear on what is being suggested and why it is an improvement. Consider using patches and the blocking or non-blocking decorations to further communicate your intent.  -->
**suggestion:** ‏That's the Persée BAIP tagger
```suggestion
## Persée BAIP Tagger

Détection d'entités nommées dans des textes anglais
```

2024-06-21 12:58 UTC, parmentf commented on services/ner-tagger/package.json
> +  "version": "0.0.0",
```suggestion
  "version": "1.0.6",
```

2024-06-21 12:58 UTC, parmentf commented on services/ner-tagger/package.json
> +  "author": " <>",
```suggestion
  "author": " <Lucas Anki>",
```

2024-06-21 12:58 UTC, parmentf commented on services/ner-tagger/swagger.json
> +        "version": "0.0.0",
```suggestion
        "version": "1.0.6",
```

2024-06-21 12:58 UTC, parmentf commented on services/ner-tagger/swagger.json
> +        "title": "ner-tagger - Détéction d'entités nommées dans des textes anglais",
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** ‏
```suggestion
        "title": "ner-tagger - Détection d'entités nommées dans des textes anglais",
```

2024-06-21 12:58 UTC, parmentf commented on services/ner-tagger/v1/geoTagger/geoTagger.ini
> +[use]
<!-- Suggestions propose improvements to the current subject. It's important to be explicit and clear on what is being suggested and why it is an improvement. Consider using patches and the blocking or non-blocking decorations to further communicate your intent.  -->
**suggestion:** ‏Generate example metadata, and insert them here

See [generate:example-metadata](https://github.com/Inist-CNRS/web-services/blob/main/SCRIPTS.md#generateexample-metadata)

2024-06-21 12:58 UTC, parmentf commented on services/ner-tagger/v1/perseeBaipTagger/tagger.ini
> +[use]
<!-- Suggestions propose improvements to the current subject. It's important to be explicit and clear on what is being suggested and why it is an improvement. Consider using patches and the blocking or non-blocking decorations to further communicate your intent.  -->
**suggestion:** ‏Generate example metadata, and insert them here

See [generate:example-metadata](https://github.com/Inist-CNRS/web-services/blob/main/SCRIPTS.md#generateexample-metadata)

2024-06-21 12:58 UTC, parmentf commented on services/ner-tagger/v1/perseeBaipTagger/tagger.ini
> +post.description = Détecte les organismes scolaires et localisations dans les baip
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** ‏
```suggestion
post.description = Détecte les organismes scolaires et localisations dans les BAIP
```

2024-06-21 13:16 UTC, parmentf requested changes

2024-06-21 13:16 UTC, parmentf commented on services/ner-tagger/package.json
> +  "description": "Détéction d'entités nommées dans des textes anglais",
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** ‏
```suggestion
  "description": "Détection d'entités nommées dans des textes anglais",
```

2024-06-25 08:04 UTC, parmentf commented on services/ner-tagger/README.md
> +Détecter des entités géographiques dans des textes anglais et d'organismes scolaires, de localisation dans des bulletins administratifs de l'instruction publique
<!-- Suggestions propose improvements to the current subject. It's important to be explicit and clear on what is being suggested and why it is an improvement. Consider using patches and the blocking or non-blocking decorations to further communicate your intent.  -->
**suggestion:** Enlever le titre de section `Persée BAIP Tagger`
‏
```suggestion
Détection d'entitées nommées:

- entités géographiques dans des textes anglais
- organismes scolaires, de localisation dans des bulletins administratifs de l'instruction publique (BAIP)
```

2024-06-25 08:05 UTC, parmentf commented on services/ner-tagger/config.json
> +        "EZS_TITLE": "Détéction d'entités nommées dans des textes anglais",
<!-- Suggestions propose improvements to the current subject. It's important to be explicit and clear on what is being suggested and why it is an improvement. Consider using patches and the blocking or non-blocking decorations to further communicate your intent.  -->
**suggestion:** ‏Not only in English texts
```suggestion
        "EZS_TITLE": "Détection d'entités nommées dans des textes",
```

2024-06-25 08:06 UTC, parmentf commented on services/ner-tagger/package.json
> +  "description": "Détection d'entités nommées dans des textes anglais",
```suggestion
  "description": "Détection d'entités nommées dans des textes",
```

2024-06-25 08:06 UTC, parmentf commented on services/ner-tagger/swagger.json
> +        "title": "ner-tagger - Détection d'entités nommées dans des textes anglais",
```suggestion
        "title": "ner-tagger - Détection d'entités nommées dans des textes",
```

2024-06-25 08:06 UTC, parmentf commented on services/ner-tagger/swagger.json
> +            "description": "Détéction d'entités nommées dans des textes anglais",
```suggestion
            "description": "Détéction d'entités nommées dans des textes",
```

2024-06-25 08:07 UTC, parmentf commented on services/ner-tagger/v1/geoTagger/geoTagger.ini
> +plugin = @ezs/analytics
<!-- Quibbles are very much like nitpick:, except it does not conjure up images of lice and animal hygiene practices.  -->
**quibble (non-blocking):** ‏`analytics` is no more required
```suggestion
```

2024-06-25 08:08 UTC, parmentf commented on services/ner-tagger/v1/perseeBaipTagger/tagger.ini
> +plugin = @ezs/analytics
<!-- Chores are simple tasks that must be done before the subject can be “officially” accepted. Usually, these comments reference some common process. Try to leave a link to the process description so that the reader knows how to resolve the chore.  -->
**chore:** ‏`analytics` is no more required
```suggestion
```

2024-06-25 08:48 UTC, AlasDiablo commented on bases/ezs-python-pytorch-server/Dockerfile
> +ENV HF_HOME=/app/.cache/transformers
Don't no, but it seem to work like that...

2024-06-25 08:49 UTC, AlasDiablo commented on bases/ezs-python-pytorch-server/Dockerfile
> +# Make sure that .npm folder is readable by the daemon user
Yes, is a copy/past typo

2024-06-25 11:39 UTC, parmentf approved these changes
There is a little change to do, but it's not critical.

2024-06-25 11:39 UTC, parmentf commented on services/ner-tagger/swagger.json
> +            "description": "Détéction d'entités nommées dans des textes",
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** ‏
```suggestion
            "description": "Détection d'entités nommées dans des textes",
```

2024-06-28 07:54 UTC, merged