Services/terms extraction/update extract quantity version
Inist-CNRS/web-services pull request #140
Opened 2024-07-22 13:44 UTC by revolj

2024-07-25 09:45 UTC, parmentf commented on services/terms-extraction/Dockerfile
> +    numpy==1.26.3 \
<!-- Suggestions propose improvements to the current subject. It's important to be explicit and clear on what is being suggested and why it is an improvement. Consider using patches and the blocking or non-blocking decorations to further communicate your intent.  -->
**suggestion:** ‏The last version before 2.0.0 for numpy is 1.26.4

See <https://pypi.org/project/numpy/#history>

We should try if it works too.
```suggestion
    numpy==1.26.4 \
```

2024-07-25 09:50 UTC, parmentf commented on services/terms-extraction/Dockerfile
> +    CQE==2.0.2 \
<!-- Quibbles are very much like nitpick:, except it does not conjure up images of lice and animal hygiene practices.  -->
**quibble (non-blocking):** ‏CQE depends on pytorch, let's use `ezs-python-pytorch-server@1.1.4` as a base image, to simplify the `Dockerfile`
And use common layers with other services

2024-07-25 09:54 UTC, parmentf commented on services/terms-extraction/Dockerfile
> +RUN npm install -g \
<!-- Questions are appropriate if you have a potential concern but are not quite sure if it's relevant or not. Asking the author for clarification or investigation can lead to a quick resolution.  -->
**question:** ‏Why did you need to install the npm packages *globally*?

2024-07-25 09:58 UTC, leogail requested changes

2024-07-25 09:58 UTC, leogail commented on services/terms-extraction/v1/quantity/extract.ini
> +post.description = Renvoie les quantités repérées dans un texte en anglais.  Renvoie la valeur en triplet (entité repérée, quantité, unité).  ^M^MUtilise la librairie [`quantulum3`](https://github.co
**praise (non-blocking):** 
```suggestion
post.description = Renvoie les quantités repérées dans un texte en anglais. Utilise la librairie [`quantulum3`](https://github.com/nielstron/quantulum3#quantulum3)
```
ça n'a plus l'air d'être des triplets en sortie. Je te proposer de supprimer cette partie ? (la sortie de la v2/ étant trop complexe pour être détaillée en une phrase).

2024-07-25 09:59 UTC, parmentf commented on services/terms-extraction/v1/quantity/extract.ini
> +post.description = Renvoie les quantités repérées dans un texte en anglais.  Renvoie la valeur en triplet (entité repérée, quantité, unité).  ^M^MUtilise la librairie [`quantulum3`](https://github.co
Je n'avais repéré, mais la ligne 6 fait encore référence à Quantulum?!?

2024-07-25 10:02 UTC, parmentf commented on services/terms-extraction/v1/quantity/extract.ini
> +post.description = Renvoie les quantités repérées dans un texte en anglais.  Renvoie la valeur en triplet (entité repérée, quantité, unité).  ^M^MUtilise la librairie [`quantulum3`](https://github.co
Il faut relancer le script `npm run insert:description services/terms-extraction/v1_quantity_extract.md`

2024-07-25 11:04 UTC, AlasDiablo commented on services/terms-extraction/Dockerfile
> +    numpy==1.26.3 \
I have propose this version because it the latest version in the pytorch indexs https://download.pytorch.org/whl/numpy/

2024-07-25 11:05 UTC, AlasDiablo commented on services/terms-extraction/Dockerfile
> +    CQE==2.0.2 \
We already tested it, be it not working beceaus CQE strictly required the version 2.0.0 of torch and we have the 2.3.0, this mean CQE reinstall it own version of torch

2024-07-25 11:28 UTC, revolj commented on services/terms-extraction/v1/quantity/extract.ini
> +post.description = Renvoie les quantités repérées dans un texte en anglais.  Renvoie la valeur en triplet (entité repérée, quantité, unité).  ^M^MUtilise la librairie [`quantulum3`](https://github.co
Oui effectivement j'ai oublié de faire les modifications de la description. Je vais modifier

2024-07-25 11:28 UTC, revolj commented on services/terms-extraction/Dockerfile
> +RUN npm install -g \
Erreur de ma part en essayant de résoudre les problèmes des versions.

2024-07-25 11:28 UTC, revolj commented on services/terms-extraction/Dockerfile
> +RUN npm install -g \
C'est corrigé.

2024-07-26 09:12 UTC, parmentf requested changes

2024-07-26 09:12 UTC, parmentf commented on services/terms-extraction/v1/quantity/extract.ini
> +post.responses.default.description = Renvoie un json comprenant les informations suivantes (quantité, unité, concepts liés) dans le champs `value`
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** ‏
```suggestion
post.responses.default.description = Renvoie un json comprenant les informations suivantes (quantité, unité, concepts liés) dans le champ `value`
```

2024-08-20 07:19 UTC, leogail approved these changes

2024-09-04 13:04 UTC, parmentf approved these changes

2024-09-04 13:35 UTC, merged