fix(data-computer): update lda parameters
Inist-CNRS/web-services pull request #153
Opened 2024-08-06 08:46 UTC by leogail

2024-08-06 08:59 UTC, leogail commented
deleted @data-computer2.12.7

Merged services/data-computer/add-corpus-similarity-ws to this branch

release @data-computer2.13.1

2024-08-07 15:07 UTC, parmentf requested changes

2024-08-07 15:07 UTC, parmentf commented on services/data-computer/tests.hurl
> +x-hook: https://webhook.site/69300b22-a251-4c16-9905-f7ba218ae7e9
<!-- Issues highlight specific problems with the subject under review. These problems can be user-facing or behind the scenes. It is strongly recommended to pair this comment with a suggestion. If you are not sure if a problem exists or not, consider leaving a question.  -->
**issue:** ‏It seems that using webhook.site in test ends with broken tests.

See #155

Moreover, that is the old webhook header (too much copy-paste): The new ones are `X-Webhook-Success` and `X-Webhook-Failure`

```suggestion
# x-hook: https://webhook.site/69300b22-a251-4c16-9905-f7ba218ae7e9
```

2024-08-07 15:07 UTC, parmentf commented on services/data-computer/v1/corpus-similarity.ini
> +post.summary = 3 sorties sont disponibles
<!-- Nitpicks are trivial preference-based requests. These should be non-blocking by nature.  -->
**nitpick (non-blocking):** ‏This should be the short description. Not a detail on the output.

```suggestion
post.summary = Similarité entre documents d'un corpus
```

2024-08-08 08:50 UTC, leogail commented on services/data-computer/README.md
> +| indent (true/false) | Indenter le résultat renvoyer immédiatement |
Aucune idée mais ça y est déjà branche principale

2024-08-08 08:54 UTC, leogail commented on services/data-computer/tests.hurl
> +x-hook: https://webhook.site/69300b22-a251-4c16-9905-f7ba218ae7e9
Cela vient de la PR de Lucas la seule chose à laquelle j'ai touché c'est `lda.py`

2024-08-08 08:54 UTC, leogail commented on services/data-computer/v1/corpus-similarity.ini
> +post.summary = 3 sorties sont disponibles
Cela vient de la PR de Lucas la seule chose à laquelle j'ai touché c'est `lda.py`

2024-08-08 08:55 UTC, closed without merging

2024-08-08 08:55 UTC, leogail commented
Je vais attendre que Lucas merge la sienne pour pas avoir toutes les modifications en double.

2024-08-09 06:53 UTC, parmentf commented on services/data-computer/README.md
> +| indent (true/false) | Indenter le résultat renvoyer immédiatement |
Oui, ça a l'air ancien.
Mais la pertinence ?