fix(affilliations-tools/ror): fix bug print
Inist-CNRS/web-services pull request #161
Opened 2024-08-08 08:33 UTC by revolj

Bug avec la sortie standard (print dans le code).

2024-08-08 11:38 UTC, parmentf commented on services/affiliations-tools/tests.hurl
> +```
<!-- TODO's are small, trivial, but necessary changes. Distinguishing todo comments from issues: or suggestions: helps direct the reader's attention to comments requiring more involvement.  -->
**todo:** ‏Use the old test, as the generated syntax, although complying to the documentation of hurl, is wrong.

2024-08-08 12:14 UTC, leogail requested changes

2024-08-08 12:14 UTC, leogail commented on services/affiliations-tools/tests.hurl
> +```
**todo (blocking):** A vérifier (les tests ne passent pas

2024-08-08 13:35 UTC, leogail commented on services/affiliations-tools/v1/ror/get-id.py
> +        print(f"Timeout error occurred: {timeout_err}",file=sys.stderr)  # La requête a expiré
Sur nos postes oui mais sur le serveur ?

2024-08-08 14:05 UTC, parmentf commented on services/affiliations-tools/v1/ror/get-id.py
> +        print(f"Timeout error occurred: {timeout_err}",file=sys.stderr)  # La requête a expiré
Normalement oui, c'est équivalent.

2024-08-20 08:44 UTC, leogail approved these changes

2024-08-20 08:44 UTC, merged