feat(text-pdf): add pdf-raw route for pdf file (instead of url)
Inist-CNRS/web-services pull request #170
Opened 2024-09-06 09:44 UTC by leogail

2024-09-09 07:52 UTC, parmentf requested changes

2024-09-09 07:52 UTC, parmentf commented on services/pdf-text/v1/pdf-raw.ini
> +post.responses.default.description = PDF au format PDF
<!-- Nitpicks are trivial preference-based requests. These should be non-blocking by nature.  -->
**nitpick (non-blocking):** ‏The response is a PDF file?!?

2024-09-09 07:52 UTC, parmentf commented on services/pdf-text/v1/pdf-raw.ini
> +post.responses.default.content.application/pdf.schema.format = binary
<!-- Nitpicks are trivial preference-based requests. These should be non-blocking by nature.  -->
**nitpick (non-blocking):** ‏I thought response was a JSON?

2024-09-09 07:52 UTC, parmentf commented on services/pdf-text/v1/pdf-raw.py
> +import random
<!-- Suggestions propose improvements to the current subject. It's important to be explicit and clear on what is being suggested and why it is an improvement. Consider using patches and the blocking or non-blocking decorations to further communicate your intent.  -->
**suggestion:** ‏Seems to be unused
```suggestion
```

2024-09-09 07:52 UTC, parmentf commented on services/pdf-text/v1/pdf-raw.py
> +@author: cuxac
<!-- Quibbles are very much like nitpick:, except it does not conjure up images of lice and animal hygiene practices.  -->
**quibble (non-blocking):** ‏Better set the real one or not set anyone
```suggestion
@author: leogail
```

2024-09-09 07:52 UTC, parmentf commented on services/pdf-text/v1/pdf-raw.py
> +    # Initlialize count variables
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** in comment‏
```suggestion
    # Initialize count variables
```

2024-09-09 07:52 UTC, parmentf commented on services/pdf-text/v1/pdf-raw.py
> +            if current_font!=None:
<!-- Polish comments are like a suggestion, where there is nothing necessarily wrong with the relevant content, there's just some ways to immediately improve the quality.  -->
**polish:** ‏Linter says...
```suggestion
            if current_font is not None:
```

2024-09-09 07:54 UTC, parmentf commented on services/pdf-text/v1/pdf-raw.py
> +@author: cuxac
If your editor don't set these metadata automatically, remove them (did you create the file on July, 3rd?).

2024-09-09 10:33 UTC, leogail commented on services/pdf-text/v1/pdf-raw.ini
> +post.responses.default.description = PDF au format PDF
**praise:** 
```suggestion
post.responses.default.description = références au fomart json
```

2024-09-09 10:33 UTC, leogail commented on services/pdf-text/v1/pdf-raw.ini
> +post.responses.default.content.application/pdf.schema.format = binary
**praise:** 
```suggestion
post.responses.default.content.application/json.schema.$ref
```

2024-09-10 15:15 UTC, parmentf submitted a review, later dismissed

2024-09-18 08:26 UTC, leogail commented on services/pdf-text/v1/pdf-raw.ini
> +
Done

2024-10-07 11:52 UTC, parmentf approved these changes

2024-10-14 12:08 UTC, merged