(sata-topcitation) Ajout du WS asynchrone sur les références phares
Inist-CNRS/web-services pull request #180
Opened 2024-09-27 13:34 UTC by revolj

2024-09-27 15:29 UTC, parmentf requested changes
Write a `tests.hurl`, you can use `data-termsuite` as an example. Two queries:

1. the call to your main route (`v1/topcitation`)
2. the call to `v1/retrieve-json` with a `delay` option, and the variable containing the value returned by the first route.

2024-09-27 15:29 UTC, parmentf commented on services/data-topcitation/Dockerfile
> +
<!-- Suggestions propose improvements to the current subject. It's important to be explicit and clear on what is being suggested and why it is an improvement. Consider using patches and the blocking or non-blocking decorations to further communicate your intent.  -->
**suggestion:** ‏If you don't use them, don't install them

It think it's part of the template, to show how to install npm packages, that's all.

```suggestion
```

2024-09-27 15:29 UTC, parmentf commented on services/data-topcitation/config.json
> +        "EZS_DESCRIPTION": "à partir d'une information (pour l'instant doi) récupère les citatio",
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** ‏
```suggestion
        "EZS_DESCRIPTION": "À partir d'une information (pour l'instant doi) récupère les citations",
```

2024-09-27 15:29 UTC, parmentf commented on services/data-topcitation/swagger.json
> +            "url": "http://vptdmservices.intra.inist.fr:49225/",
<!-- Notes are always non-blocking and simply highlight something the reader should take note of.  -->
**note (non-blocking):** ‏The final machine will be `vptdmjobs`, don't forget it when deploying!

2024-09-27 15:29 UTC, parmentf commented on services/data-topcitation/swagger.json
> +            "#DISABLED#x-profil": "Standard"
<!-- Notes are always non-blocking and simply highlight something the reader should take note of.  -->
**note (non-blocking):** At deployment, don't forget to activate `x-profil`.‏

2024-09-27 15:29 UTC, parmentf commented on services/data-topcitation/v1/retrieve-json.ini
> +post.responses.default.content.application/json.example.9.freq = 6
<!-- Polish comments are like a suggestion, where there is nothing necessarily wrong with the relevant content, there's just some ways to immediately improve the quality.  -->
**polish:** ‏Maybe you could put here an example matching your service.

2024-10-07 10:02 UTC, leogail requested changes

2024-10-07 10:02 UTC, leogail commented on services/data-topcitation/tests.hurl
> +delay: 10000
**praise:** Si ça bug, ici il faut augmenter le délai (à 10 secondes). Test avec un temps plus élevé

2024-10-08 13:01 UTC, parmentf approved these changes

2024-10-08 13:22 UTC, merged