Services/data thesesul/create service
Inist-CNRS/web-services pull request #187
Opened 2024-10-17 08:21 UTC by leogail

2024-10-17 09:54 UTC, parmentf requested changes

2024-10-17 09:54 UTC, parmentf commented on services/data-thesesul/swagger.json
> +            "name": "thesesul-sudoctohal",
<!-- Thoughts represent an idea that popped up from reviewing. These comments are non-blocking by nature, but they are extremely valuable and can lead to more focused initiatives and mentoring opportunities.  -->
**thought (non-blocking):** ‏Is it relevant to use a tag name different from the service name ? :thinking:

2024-10-17 09:54 UTC, parmentf commented on services/data-thesesul/tests.hurl
> +```
<!-- TODO's are small, trivial, but necessary changes. Distinguishing todo comments from issues: or suggestions: helps direct the reader's attention to comments requiring more involvement.  -->
**todo:** ‏Finish to write the test.

You can take a look at https://github.com/Inist-CNRS/web-services/pull/186/files#diff-bd4be06ecd6b0fa0a8e0611eee6a46a7149606ae832f4f91ad2ae2876f1b3ee1 to see how to ensure a file has the expected content.

2024-10-17 09:54 UTC, parmentf commented on services/data-thesesul/v1/charger.cfg
> +# Step 1.1 : On évite de récupere un champ uri existant
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** ‏
```suggestion
# Step 1.1 : On évite de récupérer un champ uri existant
```

2024-10-17 09:54 UTC, parmentf commented on services/data-thesesul/v1/charger.cfg
> +# Step 1.2 : On génére un identifiant unique
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** ‏
```suggestion
# Step 1.2 : On génère un identifiant unique
```

2024-10-17 09:54 UTC, parmentf commented on services/data-thesesul/v1/logger.cfg
> +# On enregistre uniqument quelques informations (à supprimer pour avoir la trace complète)
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** ‏
```suggestion
# On enregistre uniquement quelques informations (à supprimer pour avoir la trace complète)
```

2024-10-17 09:54 UTC, parmentf commented on services/data-thesesul/v1/recorder.cfg
> +# # Step 2.2 (générique): Création d'un fichier résulat standard
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** ‏
```suggestion
# # Step 2.2 (générique): Création d'un fichier résultat standard
```

2024-10-17 09:54 UTC, parmentf commented on services/data-thesesul/v1/recorder.cfg
> +# # Step 2.3 (générique): Sauvegarder sur disque le résulat
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** ‏
```suggestion
# # Step 2.3 (générique): Sauvegarder sur disque le résultat
```

2024-10-17 09:54 UTC, parmentf commented on services/data-thesesul/v1/recorder.cfg
> +# Step 2.4 (générique): Signaler le fin du traitement via un appel à un webhook (si il a été précisé)
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** ‏
```suggestion
# Step 2.4 (générique): Signaler la fin du traitement via un appel à un webhook (s'il a été précisé)
```

2024-10-17 09:54 UTC, parmentf commented on services/data-thesesul/v1/recorder.cfg
> +# Step 2.4.1 (générique): Séléctionner les informations à envoyer au webhook
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** ‏
```suggestion
# Step 2.4.1 (générique): Sélectionner les informations à envoyer au webhook
```

2024-10-17 09:54 UTC, parmentf commented on services/data-thesesul/v1/recorder.cfg
> +# Step 2.4.3 (faculatif) : Ajouter une trace dans log
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** ‏
```suggestion
# Step 2.4.3 (facultatif) : Ajouter une trace dans log
```

2024-10-17 09:54 UTC, parmentf commented on services/data-thesesul/v1/recorder.cfg
> +# Step 2.5 (faculatif) : Ajouter une trace dans log
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** ‏
```suggestion
# Step 2.5 (facultatif) : Ajouter une trace dans log
```

2024-10-17 09:54 UTC, parmentf commented on services/data-thesesul/v1/sudoc.ini
> +# Step 2 (générique): Traiter de manière asynchnore les items reçus
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** ‏
```suggestion
# Step 2 (générique): Traiter de manière asynchrone les items reçus
```

2024-10-17 09:54 UTC, parmentf commented on services/data-thesesul/v1/sudoc.ini
> +# Step 2.2 (générique): Enregister le résulat et signaler que le traitment est fini
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** ‏
```suggestion
# Step 2.2 (générique): Enregistrer le résultat et signaler que le traitement est fini
```

2024-10-17 09:54 UTC, parmentf commented on services/data-thesesul/v1/sudoc.ini
> +# Step 3 : Renvoyer immédiatement un seul élément indiquant comment récupérer le résulat quand il sera prêt
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** ‏
```suggestion
# Step 3 : Renvoyer immédiatement un seul élément indiquant comment récupérer le résultat quand il sera prêt
```

2024-10-17 09:54 UTC, parmentf commented on services/data-thesesul/v1/sudoc.py
> +OUTPUT_DIR = os.path.join(TMP_DIR, "retrieve", retrieve_id, "datas")
**polish:** Make it clearer and easier to maintain (less duplicate code)

```suggestion
OUTPUT_DIR = os.path.join(TMP_DIR, "retrieve", retrieve_id, "datas")
os.makedirs(OUTPUT_DIR, exist_ok=True)
```

2024-10-17 09:54 UTC, parmentf commented on services/data-thesesul/v1/sudoc.py
> +    cmd = f'cd /tmp/retrieve/{retrieve_id} && tar -czf /tmp/retrieve/{retrieve_id}.tar.gz . && cd /app/public/ && rm -r /tmp/retrieve/{retrieve_id} && mv /tmp/retrieve/{retrieve_id}.tar.gz /tmp/retri
<!-- Suggestions propose improvements to the current subject. It's important to be explicit and clear on what is being suggested and why it is an improvement. Consider using patches and the blocking or non-blocking decorations to further communicate your intent.  -->
**suggestion:** ‏Make it clearer using shorter lines

```suggestion
cmd = (f'cd /tmp/retrieve/{retrieve_id} && '
       f'tar -czf /tmp/retrieve/{retrieve_id}.tar.gz . && '
       f'cd /app/public/ && '
       f'rm -r /tmp/retrieve/{retrieve_id} && '
       f'mv /tmp/retrieve/{retrieve_id}.tar.gz /tmp/retrieve/{retrieve_id}')
```

2024-10-17 09:55 UTC, parmentf commented
Why do you use DVC to manager XSL files?
I think it's more code than data...

2024-10-17 14:49 UTC, leogail commented on services/data-thesesul/v1/sudoc.py
> +OUTPUT_DIR = os.path.join(TMP_DIR, "retrieve", retrieve_id, "datas")
Ah oui j'ai fait fort

2024-10-21 09:50 UTC, parmentf requested changes

2024-10-21 09:50 UTC, parmentf commented on services/data-thesesul/v1/retrieve-tests.py
> +    sys.stdout.write(json.dumps({"value":"False"}))
<!-- Suggestions propose improvements to the current subject. It's important to be explicit and clear on what is being suggested and why it is an improvement. Consider using patches and the blocking or non-blocking decorations to further communicate your intent.  -->
**suggestion:** ‏Remove the extracted files in /tmp

Such that next test won't think it's OK, only because previous tests was OK

2024-10-21 09:50 UTC, parmentf commented on services/data-thesesul/v1/retrieve.ini
> +post.description = Ce retrieve est spécifique : il permet de récupérer le dossier résultat de la route `sudoc`. Le dossier est compressé au format .tar.gz. Il est constitué d'un fichier logs.csv, per
<!-- Polish comments are like a suggestion, where there is nothing necessarily wrong with the relevant content, there's just some ways to immediately improve the quality.  -->
**polish:** ‏Add a bit of Markdown.
```suggestion
post.description = Ce `retrieve` est spécifique : il permet de récupérer le dossier résultat de la route `sudoc`. Le dossier est compressé au format `.tar.gz`. Il est constitué d'un fichier `logs.csv`, permettant d'afficher tous les `id`s des documents qui n'ont pas pu être transformés, et d'un dossier `/datas` contenant tous les fichiers `xml`s et `pdf`s.
```

2024-10-21 09:50 UTC, parmentf commented on services/data-thesesul/v1/sudoc.ini
> +post.description = A partir d'identifiants Sudoc, ce service web télécharge les XML et PDF en provenance du Sudoc. Les XML sont transformés dans un format TEI pour import dans Hal. Le résultat de ce
<!-- Questions are appropriate if you have a potential concern but are not quite sure if it's relevant or not. Asking the author for clarification or investigation can lead to a quick resolution.  -->
**question:** ‏Where is the end of the last sentence ?!?

2024-10-21 13:28 UTC, parmentf approved these changes

2024-10-22 07:49 UTC, merged