(affiliations-tools/ror) change geonames path
Inist-CNRS/web-services pull request #196
Opened 2024-10-29 15:50 UTC by revolj

2024-10-30 08:59 UTC, leogail requested changes
ok, à part le tests.hurl à vérifier

2024-10-30 08:59 UTC, leogail commented on services/affiliations-tools/tests.hurl
**question (blocking):** Tu sais pourquoi les tests ne sont pas passés ?

2024-10-30 12:47 UTC, revolj commented on services/affiliations-tools/tests.hurl
Peut être l'indention ? Je vais regénérer le `tests.hurl`

2024-10-30 14:26 UTC, leogail commented on services/affiliations-tools/tests.hurl
Dis moi quand c'est modifié

2024-10-30 15:13 UTC, revolj commented on services/affiliations-tools/tests.hurl
Bon c'était bien un problème dans le json je pense, c'est bon les tests sont passés.

2024-11-05 06:43 UTC, leogail approved these changes

2024-11-07 10:28 UTC, parmentf approved these changes

2024-11-07 15:00 UTC, merged