Fix:Output will now be concidered as list as it was expected
Inist-CNRS/web-services pull request #198
Opened 2024-11-05 10:36 UTC by Luc-Ank

Fix output to be a list and not a string representation of a list

2024-11-05 12:15 UTC, leogail commented
tu sais pourquoi les tests ne passent pas ?
Tu as généré les tests avec la commance `npm run generate:example-tests services/service-name` ?

2024-11-05 12:21 UTC, Luc-Ank commented
Y'a un problème avec le format de la sortie qui semple être différente de celui du fichier hurl, bien que le fichier hurl soit juste un copié collé de la sortie du WS. J'essaye de comprendre pourquoi

2024-11-05 13:35 UTC, leogail commented
A faire attention :
- l'indentation
- Fonction d'où tu copies, le format peut être différent (string alors que hurl attend un json).

En lançant la commande pour générer les tests tu évites ces problèmes.
Si c'est autre chose je sais pas

2024-11-12 10:39 UTC, parmentf commented
You can now create a new version.
Maybe use a major one, as this changes the behaviour of the route.

2024-11-22 12:56 UTC, parmentf requested changes
Once you have a container in production, update `swagger.json`, and we'll publish it.
Next, we will merge this PR.

2024-11-27 12:41 UTC, parmentf approved these changes

2024-11-27 12:41 UTC, merged