perf(biblio-ref): add premium crossref token
Inist-CNRS/web-services pull request #200
Opened 2024-11-06 09:56 UTC by leogail

2024-11-06 09:58 UTC, leogail commented
Les tests ne passent pas : il faut ajouter la variable d'environnement CROSSREF_API_KEY dans les secrets github

2024-11-06 10:38 UTC, parmentf requested changes
Improve your README.md.

We still have to add `CROSSREF_API_KEY` as a secret variable, for the tests to pass.

2024-11-06 10:38 UTC, parmentf commented on services/biblio-ref/README.md
> +Nécessite une variable d'environnement `API_TOKEN`, un token pour utiliser l'API Crossref. Elle doit se trouver dans un un fichier `.env` à la racine.
<!-- Issues highlight specific problems with the subject under review. These problems can be user-facing or behind the scenes. It is strongly recommended to pair this comment with a suggestion. If you are not sure if a problem exists or not, consider leaving a question.  -->
**issue:** I thought the env var was `CROSSREF_API_KEY`, not `API_TOKEN`...‏

2024-11-06 10:41 UTC, leogail commented on services/biblio-ref/README.md
> +Nécessite une variable d'environnement `API_TOKEN`, un token pour utiliser l'API Crossref. Elle doit se trouver dans un un fichier `.env` à la racine.
I changed it after seeing how you names openalex env var but forgot it in readme. Done.

2024-11-06 10:42 UTC, leogail commented on services/biblio-ref/README.md
> +Nécessite une variable d'environnement `API_TOKEN`, un token pour utiliser l'API Crossref. Elle doit se trouver dans un un fichier `.env` à la racine.
**praise:** 
```suggestion
Nécessite une variable d'environnement `CROSSREF_API_KEY`, un token pour utiliser l'API Crossref. Elle doit se trouver dans un un fichier `.env` à la racine (voir le fichier .env.example associé)
```

2024-11-06 10:47 UTC, parmentf approved these changes

2024-11-07 16:05 UTC, parmentf commented on services/biblio-ref/config.json
> +        "EZS_CONCURRENCY": 3,
<!-- Notes are always non-blocking and simply highlight something the reader should take note of.  -->
**note (non-blocking):** 3 is still very large for `EZS_CONCURRENCY`

This variable is used to prepare enough process to answer to many requests, not to execute many processes for one request. I think you misunderstood something.‏

2024-11-08 10:51 UTC, merged