Services/data rapido/create data rapido
Inist-CNRS/web-services pull request #201
Opened 2024-11-07 10:52 UTC by Luc-Ank

Remove Rapido from data-computer and move it to it's own repository.
Adding one route for phase 1 and one route for phase 2 (Machine learning with custom model)

2024-11-12 13:59 UTC, parmentf requested changes

2024-11-12 13:59 UTC, parmentf commented on services/data-rapido/v1/charger-xml.cfg
> +# Step 1.1 : On évite de récupere un champ uri existant
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** ‏
```suggestion
# Step 1.1 : On évite de récupérer un champ uri existant
```

2024-11-12 13:59 UTC, parmentf commented on services/data-rapido/v1/charger-xml.cfg
> +# Step 1.2 : On génére un identifiant unique
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** ‏
```suggestion
# Step 1.2 : On génère un identifiant unique
```

2024-11-12 13:59 UTC, parmentf commented on services/data-rapido/v1/logger.cfg
> +# On ne garde que la première erreur déclénchée
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** ‏
```suggestion
# On ne garde que la première erreur déclenchée
```

2024-11-12 13:59 UTC, parmentf commented on services/data-rapido/v1/logger.cfg
> +; [use]
<!-- Thoughts represent an idea that popped up from reviewing. These comments are non-blocking by nature, but they are extremely valuable and can lead to more focused initiatives and mentoring opportunities.  -->
**thought (non-blocking):** ‏I wonder why `[use]` is commented out. :thinking: 

Maybe because these plugins are already loaded by the calling scripts?
It may slow down the process to try to load them again...

2024-11-12 13:59 UTC, parmentf commented on services/data-rapido/v1/logger.cfg
> +# On enregistre uniqument quelques informations (à supprimer pour avoir la trace complète)
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** ‏
```suggestion
# On enregistre uniquement quelques informations (à supprimer pour avoir la trace complète)
```

2024-11-12 13:59 UTC, parmentf commented on services/data-rapido/v1/rapido-algorithme.ini
>  post.description = Web service à destination du projet rapido. Ce web service prend en entrée un tar.gz comportant un dossier data incluant tout les documents xml à traiter. Il renvoit un json compor
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** ‏
```suggestion
post.description = Web service à destination du projet rapido. Ce web service prend en entrée un `tar.gz` comportant un dossier `data` incluant tous les documents xml à traiter. Il renvoie un json comportant les alignements que l'algorithme a pu faire entre le texte et le référentiel idRef.
```

2024-11-12 13:59 UTC, parmentf commented on services/data-rapido/v1/rapido-algorithme.ini
> +post.summary = Applique un algorithme de recherche d'entitées et d'alignement avec idRef. Prévu dans le cadre de la phase 1 du projet Rapido.
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** ‏
```suggestion
post.summary = Applique un algorithme de recherche d'entités et d'alignement avec idRef. Prévu dans le cadre de la phase 1 du projet Rapido.
```

2024-11-12 13:59 UTC, parmentf commented on services/data-rapido/v1/rapido-apprentissage.ini
> +post.description = Web service à destination du projet rapido. Ce web service prend en entrée un tar.gz comportant un dossier data incluant tout les documents xml à traiter. Il renvoit un json compor
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** ‏
```suggestion
post.description = Web service à destination du projet rapido. Ce web service prend en entrée un `tar.gz` comportant un dossier `data` incluant tout les documents xml à traiter. Il renvoie un json comportant les alignements que l'algorithme a pu faire entre le texte et le référentiel idRef.
```

2024-11-12 13:59 UTC, parmentf commented on services/data-rapido/v1/rapido-apprentissage.ini
> +post.summary = Détecte des entitées via un modèle d'IA puis applique un algorithme d'alignement avec idRef. Prévu dans le cadre de la phase 2 du projet Rapido.
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** ‏
```suggestion
post.summary = Détecte des entités via un modèle d'IA puis applique un algorithme d'alignement avec idRef. Prévu dans le cadre de la phase 2 du projet Rapido.
```

2024-11-12 13:59 UTC, parmentf commented on services/data-rapido/v1/rapido-apprentissage.ini
> +# Step 2 (générique): Traiter de manière asynchnore les items reçus
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** ‏
```suggestion
# Step 2 (générique): Traiter de manière asynchrone les items reçus
```

2024-11-12 13:59 UTC, parmentf commented on services/data-rapido/v1/rapido-apprentissage.ini
> +# Step 2.2 (générique): Enregister le résulat et signaler que le traitment est fini
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** ‏
```suggestion
# Step 2.2 (générique): Enregistrer le résultat et signaler que le traitement est fini
```

2024-11-12 13:59 UTC, parmentf commented on services/data-rapido/v1/logger.cfg
> +; [use]
No, the calling scripts don't include `analytics`.
That means that `analytics` has to be already loaded in the server's memory.
Strange, perhaps there are cases where, according to the calling order of routes, that won't work. :thinking:

2024-11-12 13:59 UTC, parmentf commented on services/data-rapido/v1/rapido.py
> +    app = False
<!-- Suggestions propose improvements to the current subject. It's important to be explicit and clear on what is being suggested and why it is an improvement. Consider using patches and the blocking or non-blocking decorations to further communicate your intent.  -->
**suggestion:** ‏A detail, but we could reduce code length
```suggestion
app = False
if '-p' in sys.argv:
    arg = int(sys.argv[sys.argv.index('-p') + 1])
    if arg != 0:
        app = True
```

2024-11-12 13:59 UTC, parmentf commented on services/data-rapido/v1/rapido/alignment.py
> +                                        subDic["text"].append(sentence.to_original_text())
<!-- Thoughts represent an idea that popped up from reviewing. These comments are non-blocking by nature, but they are extremely valuable and can lead to more focused initiatives and mentoring opportunities.  -->
**thought (non-blocking):** ‏A lot of nesting, there... time for new functions/methods?

This ends with being hard to read.
Splitting the body of this method by calling other methods could clarify the code (especially with well-named methods)...

2024-11-12 13:59 UTC, parmentf commented on services/data-rapido/v1/buffer.cfg
> +# et répondre rapidement au client que le traitmenent asynchnrone est lancé.
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** ‏
```suggestion
# et répondre rapidement au client que le traitement asynchrone est lancé.
```

2024-11-12 13:59 UTC, parmentf commented on services/data-rapido/v1/rapido/annotations_old_backup.csv
The new name of this file implies that it won't be used any more.
Better remove it (as it *is* included in the docker image)

2024-11-12 13:59 UTC, parmentf commented on services/data-rapido/v1/recorder.cfg
> +# Step 2.2 (générique): Création d'un fichier résulat standard
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** ‏
```suggestion
# Step 2.2 (générique): Création d'un fichier résultat standard
```

2024-11-12 13:59 UTC, parmentf commented on services/data-rapido/v1/recorder.cfg
> +# Step 2.3 (générique): Sauvegarder sur disque le résulat
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** ‏
```suggestion
# Step 2.3 (générique): Sauvegarder sur disque le résultat
```

2024-11-12 13:59 UTC, parmentf commented on services/data-rapido/v1/recorder.cfg
> +# Step 2.4 (générique): Signaler le fin du traitement via un appel à un webhook (si il a été précisé)
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** ‏
```suggestion
# Step 2.4 (générique): Signaler la fin du traitement via un appel à un webhook (s'il a été précisé)
```

2024-11-12 13:59 UTC, parmentf commented on services/data-rapido/v1/recorder.cfg
> +# Step 2.4.2 (générique): Envoyer la requète HTTP
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** ‏
```suggestion
# Step 2.4.2 (générique): Envoyer la requête HTTP
```

2024-11-13 07:56 UTC, Luc-Ank commented on services/data-rapido/v1/rapido/alignment.py
> +                                        subDic["text"].append(sentence.to_original_text())
Yes i've planned to add a lot of commentary, change function and variable names, and rearrange as much as possible later in a new PR

2024-11-13 12:37 UTC, Luc-Ank commented on services/data-computer/README.md
> -
I double checked and spacy is needed for lda

2024-11-22 12:58 UTC, parmentf requested changes
Once a container is in production, update `swagger.json` (with the right machine name, and port) set the `Waiting make publish` label to the PR.

2024-11-27 10:38 UTC, parmentf requested changes

2024-11-27 10:38 UTC, parmentf commented on services/data-rapido/swagger.json
> +            "#DISABLED#x-profil": "Standard"
<!-- Issues highlight specific problems with the subject under review. These problems can be user-facing or behind the scenes. It is strongly recommended to pair this comment with a suggestion. If you are not sure if a problem exists or not, consider leaving a question.  -->
**issue:** ‏Enable & on the right machine

```suggestion
            "url": "http://vptdmjobss.intra.inist.fr:49203/",
            "description": "Latest version for production",
            "x-profil": "Standard"
```

2024-11-28 08:30 UTC, parmentf approved these changes

2024-11-28 08:57 UTC, merged