feat(data-thesesul): breaking change : changed output
Inist-CNRS/web-services pull request #204
Opened 2024-11-08 10:46 UTC by leogail

Now, the output is a set of zip (or xml when can't retrieve pdf on sudoc)

2024-11-08 13:07 UTC, parmentf commented
Could you use this PR to fix #191 ?

2024-11-12 14:26 UTC, parmentf requested changes

2024-11-12 14:26 UTC, parmentf commented on services/data-thesesul/README.md
> +- Vérifier que le dossier datas contient autant de fichiers que d'identifiants en entrée. Il peut y avoir un léger écart : vérifier que ces fichiers sont bien en erreur dans les logs. Très important
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** ‏
```suggestion
- Vérifier que le dossier datas contient autant de fichiers que d'identifiants en entrée. Il peut y avoir un léger écart : vérifier que ces fichiers sont bien en erreur dans les logs. Très important : l'erreur "Le PDF n'a pas pu être récupérée" n'est pas bloquante et ne doit donc pas être comptabilisée dans cette vérification.
```

Moreover: data is invariant, it has no plural form.

2024-11-12 14:26 UTC, parmentf commented on services/data-thesesul/README.md
> +- Concernant le dossier datas, il est consituté d'un ensemble de fichier x.zip ou x.xml (où x est l'identifiant du Sudoc en entrée). Si le fichier est en .xml, c'est qu'il a été impossible de récupér
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** ‏
```suggestion
- Concernant le dossier datas, il est constitué d'un ensemble de fichier `x.zip` ou `x.xml` (où `x` est l'identifiant du Sudoc en entrée). Si le fichier est en `.xml`, c'est qu'il a été impossible de récupérer le PDF et il sera *push* sans (et c'est indiqué dans le fichier de logs)
```

2024-11-12 14:26 UTC, parmentf commented on services/data-thesesul/README.md
> +- (En test encore): Ensuite, on utilise le script bash `v1/push-on-hal.sh` pour push l'ensemble des fichiers de ce dossier. Après avoir vérifier que le script est exécutable, le script peut être simp
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** ‏
```suggestion
- (En test encore): Ensuite, on utilise le script bash `v1/push-on-hal.sh` pour push l'ensemble des fichiers de ce dossier. Après avoir vérifié que le script est exécutable, le script peut être simplement utilisé comme suit : `./send_files.sh /chemin/vers/dossier/datas`.
```

2024-11-12 14:26 UTC, parmentf commented on services/data-thesesul/v1/retrieve-tests.py
Won't you use the generic test (using sha256, like in [`data-wrappers`](https://github.com/Inist-CNRS/web-services/blob/ac562c0ab179afb84f2054e8f46a84db41455414/services/data-wrapper/tests.hurl#L68-L75))?
So that you can remove the `retrieve-tests` route...
It would fix #191

2024-11-12 14:26 UTC, parmentf commented on services/data-thesesul/v1/sudoc.py
> +from thesesul.thesesul_functions import *
<!-- Praises highlight something positive. Try to leave at least one of these comments per review. Do not leave false praise (which can actually be damaging). Do look for something to sincerely praise.  -->
**praise:** ‏Well done!

2024-11-12 14:26 UTC, parmentf commented on services/data-thesesul/v1/sudoc.py
> +                            else:
<!-- Suggestions propose improvements to the current subject. It's important to be explicit and clear on what is being suggested and why it is an improvement. Consider using patches and the blocking or non-blocking decorations to further communicate your intent.  -->
**suggestion:** The whole `try/finally` lines could be in a function, lightening the main code...

Also, I wonder if there is a way to better handle all these nested `if` to make them more readable.‏

2024-11-12 14:26 UTC, parmentf commented on services/data-thesesul/v1/sudoc.py
> +                            else:
You could have a structure like that:

```py
sudoc_file = get_xml_from_sudoc(sudoc_id)
cond_file = transform_sudoc_to_conditor(sudoc_file)
tei_hal_file = transform_conditor_to_tei_hal(cond_file)
...
```

where the conditions are at the beginning of the functions.

```py
def transform_sudoc_to_conditor(sudoc_file):
  if not sudoc_file:
    return None
  ...
```

2024-11-14 12:31 UTC, leogail commented on services/data-thesesul/v1/sudoc.py
> +                            else:
done

2024-11-14 13:18 UTC, leogail commented on services/data-thesesul/v1/retrieve-tests.py
I'll need help for this

2024-11-15 10:59 UTC, parmentf approved these changes

2024-11-20 10:42 UTC, merged