refactor(affiliation-rnsr): migrate service affiliation-rnsr
Inist-CNRS/web-services pull request #39
Opened 2024-01-31 14:17 UTC by leogail

There is an error : can build the image but can't start it.

To know : 
- I build it using inistcnrs/lodex-workers-python:4.0.11 instead of cnrsinist/ezs-python-server:py3.9-no16-1.0.6.
(beacause fasttext has some issues for python 3.9+)
- have 2 roots instead of one (v2 and v3). I changed it in .dockerignore.

2024-01-31 14:41 UTC, leogail commented
It worked using the image cnrsinist/ezs-python-server:py3.9-no16-1.0.6. I had generated tests.
Now, it seems like there is pbs with secrets

2024-02-01 10:09 UTC, parmentf commented
> It worked using the image cnrsinist/ezs-python-server:py3.9-no16-1.0.6. I had generated tests. Now, it seems like there is pbs with secrets

That's because I did not update `package.json` in the template.

You have to modify your `package.json` according to what we did in `biblio-ref`: https://github.com/Inist-CNRS/web-services/blob/main/services/biblio-ref/package.json#L28

```json
       "build:dev": ". ./.env 2> /dev/null; DOCKER_BUILDKIT=1 docker build -t cnrsinist/${npm_package_name}:latest --secret id=webdav_login,env=WEBDAV_LOGIN --secret id=webdav_password,env=WEBDAV_PASSWORD --secret id=webdav_url,env=WEBDAV_URL .",
...
       "build": ". ./.env 2> /dev/null; DOCKER_BUILDKIT=1 docker build -t cnrsinist/${npm_package_name}:${npm_package_version} --secret id=webdav_login,env=WEBDAV_LOGIN --secret id=webdav_password,env=WEBDAV_PASSWORD --secret id=webdav_url,env=WEBDAV_URL .",
```

2024-02-01 10:12 UTC, parmentf commented on services/affiliation-rnsr/README.md
> +Pour chaque affiliation séparées par un point virgule, retourne un RNSR. Retourne n/a si aucun RNSR n'est trouvé.
Talk about the `.env` file.
See `biblio-ref` README.

2024-02-01 10:27 UTC, parmentf requested changes

2024-02-01 10:27 UTC, parmentf commented on services/affiliation-rnsr/v3/affiliation/rnsr.ini
> +post.responses.default.description = Renvoie un Json composé d'`id`, `value` avec `value` le RNSR trouvé
<!-- Suggestions propose improvements to the current subject. It's important to be explicit and clear on what is being suggested and why it is an improvement. Consider using patches and the blocking or non-blocking decorations to further communicate your intent.  -->
**suggestion:** ‏It returns an array in `value`

```suggestion
post.responses.default.description = Renvoie un Json composé d'`id`, `value` avec `value` le tableau des RNSR trouvés
```

2024-02-01 10:27 UTC, parmentf commented on services/affiliation-rnsr/v2/affiliation/rnsr.ini
**Question**: Isn't `affiliation` in the route redundant with the service name `affiliation-rnsr`?

The route would be shorter, and simpler, if the path to `rnsr.ini` was `v2` instead of `v2/affliation`.
As a result, the URL would be `https://affiliation-rnsr.services.istex.fr/v2/rnsr` instead of `https://affiliation-rnsr.services.istex.fr/v2/affiliation/rnsr`.

2024-02-01 10:27 UTC, parmentf commented on services/affiliation-rnsr/v3/affiliation/models.dvc
**Question**: Isn't `affiliation` in the route redundant with the service name `affiliation-rnsr`?

Same remark as for `v2/affiliation`.

The route would be shorter, and simpler, if the path to `rnsr.ini` was `v3` instead of `v3/affliation`.
As a result, the URL would be `https://affiliation-rnsr.services.istex.fr/v3/rnsr` instead of `https://affiliation-rnsr.services.istex.fr/v3/affiliation/rnsr`.

2024-02-01 10:27 UTC, parmentf commented on services/affiliation-rnsr/package.json
> +        "build:dev": "docker build -t cnrsinist/${npm_package_name}:latest .",
<!-- Issues highlight specific problems with the subject under review. These problems can be user-facing or behind the scenes. It is strongly recommended to pair this comment with a suggestion. If you are not sure if a problem exists or not, consider leaving a question.  -->
**issue:** The called version of docker don't use secrets

‏
```suggestion
        "build:dev": ". ./.env 2> /dev/null; DOCKER_BUILDKIT=1 docker build -t cnrsinist/${npm_package_name}:latest --secret id=webdav_login,env=WEBDAV_LOGIN --secret id=webdav_password,env=WEBDAV_PASSWORD --secret id=webdav_url,env=WEBDAV_URL .",
```

2024-02-01 10:27 UTC, parmentf commented on services/affiliation-rnsr/package.json
> +        "build": "docker build -t cnrsinist/${npm_package_name}:${npm_package_version} .",
```suggestion
        "build": ". ./.env 2> /dev/null; DOCKER_BUILDKIT=1 docker build -t cnrsinist/${npm_package_name}:${npm_package_version} --secret id=webdav_login,env=WEBDAV_LOGIN --secret id=webdav_password,env=WEBDAV_PASSWORD --secret id=webdav_url,env=WEBDAV_URL .",
```

2024-02-01 10:30 UTC, leogail commented on services/affiliation-rnsr/v3/affiliation/models.dvc
Right, i'll change it

2024-02-01 10:42 UTC, parmentf commented on services/affiliation-rnsr/v2/affiliation/rnsr.ini
As the route is already existing and used, don't change it.

2024-02-01 10:43 UTC, parmentf commented on services/affiliation-rnsr/v3/affiliation/models.dvc
Only for the next versions, as it is already in production.

2024-02-01 10:49 UTC, parmentf approved these changes

2024-02-01 14:55 UTC, merged