Services/diseases ner/migrate
Inist-CNRS/web-services pull request #49
Opened 2024-02-21 15:03 UTC by leogail

2024-02-21 15:57 UTC, parmentf requested changes

2024-02-21 15:57 UTC, parmentf commented on services/diseases-ner/README.md
> +Renvoie un Json composé comportant un champs `diseases` correspondant aux entités nommées de maladies trouvées
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** ‏
```suggestion
Renvoie un Json composé comportant un champ `diseases` correspondant aux entités nommées de maladies trouvées
```

2024-02-21 15:57 UTC, parmentf commented on services/diseases-ner/config.json
> +        "EZS_DESCRIPTION": "Renvoie un Json composé comportant un champs `diseases` correspondant aux entités nommées de maladies trouvées",
```suggestion
        "EZS_DESCRIPTION": "Renvoie un Json composé comportant un champ `diseases` correspondant aux entités nommées de maladies trouvées",
```

2024-02-21 15:57 UTC, parmentf commented on services/diseases-ner/examples.http
> +# Description de la route
<!-- Nitpicks are trivial preference-based requests. These should be non-blocking by nature.  -->
**nitpick (non-blocking):** ‏Adapt name and description to the service

```suggestion
# @name v1diseasesTagger
# Trouve les entités nommées de maladies
```

2024-02-21 15:57 UTC, parmentf commented on services/diseases-ner/tests.hurl
> +        "diseases": [
<!-- Thoughts represent an idea that popped up from reviewing. These comments are non-blocking by nature, but they are extremely valuable and can lead to more focused initiatives and mentoring opportunities.  -->
**thought (non-blocking):** Pourquoi imbriquer `diseases` dans `values`

You return only one field, why not use `value`, and put the array at this level?
Do you plan to add other fields?
See [YAGNI](https://fr.wikipedia.org/wiki/YAGNI)

2024-02-21 15:57 UTC, parmentf commented on services/diseases-ner/v1/diseases/tagger.ini
> +post.responses.default.description = Renvoie un Json composé comportant un champs `value` correspondant aux entités de maladies trouvées
```suggestion
post.responses.default.description = Renvoie un Json composé comportant un champ `value` correspondant aux entités de maladies trouvées
```

2024-02-21 16:04 UTC, leogail commented on services/diseases-ner/tests.hurl
> +        "diseases": [
Two reasons : 
- being the most consistent with other ws doing NER
- Can add a field "disease_disambiguisate" later without breaking change

2024-03-04 16:08 UTC, parmentf approved these changes

2024-03-05 14:47 UTC, merged