docs(CONTRIBUTING.md): added dvc subsection
Inist-CNRS/web-services pull request #51
Opened 2024-02-22 10:55 UTC by leogail

non optimal pipeline for now (look at first point and 'remarque') but non-breaking with git architecture

2024-02-23 09:09 UTC, parmentf requested changes
Few improvements to do.

2024-02-23 09:09 UTC, parmentf commented on CONTRIBUTING.md
> +
<!-- Polish comments are like a suggestion, where there is nothing necessarily wrong with the relevant content, there's just some ways to immediately improve the quality.  -->
**polish:** Remove shebang

It is not useful in a `.env` that you import via `. .env`, on the contrary to a `env.bash` that you run via `./env.bash`.

```suggestion
```

2024-02-23 09:09 UTC, parmentf commented on CONTRIBUTING.md
> +  - Initier un dépot DVC en faisant `git init` puis `dvc init`.
<!-- Thoughts represent an idea that popped up from reviewing. These comments are non-blocking by nature, but they are extremely valuable and can lead to more focused initiatives and mentoring opportunities.  -->
**thought (non-blocking):** ‏Only if not already in a git repo.

2024-02-23 09:09 UTC, parmentf commented on CONTRIBUTING.md
> +- modifier les scripts `build:dev` et `build` du fichier `package.json`
<!-- Quibbles are very much like nitpick:, except it does not conjure up images of lice and animal hygiene practices.  -->
**quibble (non-blocking):** of the service
‏
```suggestion
- modifier les scripts `build:dev` et `build` du fichier `package.json` du service
```

2024-02-23 09:09 UTC, parmentf commented on CONTRIBUTING.md
> +- modifier le dockerfile en conséquent, en s'inspirant du dockerfile de `biblio-ref`
```suggestion
- modifier le `Dockerfile` en conséquence, en s'inspirant du [Dockerfile de `biblio-ref`](https://github.com/Inist-CNRS/web-services/blob/main/services/biblio-ref/Dockerfile)
```

2024-03-06 10:18 UTC, leogail commented on CONTRIBUTING.md
> +  - Initier un dépot DVC en faisant `git init` puis `dvc init`.
modifié : Initier un dépot DVC en faisant `dvc init` (nécessite d'être dans un repo git).

2024-03-12 09:54 UTC, merged