feat(pdf-text): create service
Inist-CNRS/web-services pull request #52
Opened 2024-02-28 13:27 UTC by leogail

2024-03-04 16:29 UTC, parmentf commented
It seems similar to #29

2024-03-12 08:22 UTC, parmentf commented
> It seems similar to #29

But is more advanced than #29

2024-03-19 11:02 UTC, parmentf requested changes

2024-03-19 11:02 UTC, parmentf commented on services/pdf-text/v1/pdf2txt.py
> +
<!-- Polish comments are like a suggestion, where there is nothing necessarily wrong with the relevant content, there's just some ways to immediately improve the quality.  -->
**polish:** ‏Remove dead code

2024-03-19 11:02 UTC, parmentf commented on services/pdf-text/v1/pdf2txt.py
> +            #if len(linef)>4:
<!-- Nitpicks are trivial preference-based requests. These should be non-blocking by nature.  -->
**nitpick (non-blocking):** ‏Remove dead code

That will only question future readers

2024-03-21 10:10 UTC, leogail commented on services/pdf-text/v1/pdf2txt.py
> +#    ]))
**suggestion (non-blocking):** 
```suggestion
```

2024-03-21 10:10 UTC, leogail commented on services/pdf-text/v1/pdf2txt.py
> +
**praise:** 
```suggestion
```

2024-03-21 10:12 UTC, leogail commented on services/pdf-text/v1/pdf2txt.py
> +        sys.stderr.write("La conversion PDF vers XML a échoué.")
**praise:** 
```suggestion
        sys.stderr.write(f"Conversion of PDF {input_path} to XML has failed.")
```

2024-03-21 10:13 UTC, leogail commented on services/pdf-text/v1/pdf2txt.py
> +
**suggestion (non-blocking):** 
```suggestion
```

2024-03-21 10:13 UTC, leogail commented on services/pdf-text/v1/pdf2txt.py
> +            #if len(linef)>4:
**suggestion (non-blocking):** 
```suggestion
```

2024-03-21 10:59 UTC, parmentf commented on services/pdf-text/.dockerignore
> +!tmp
<!-- Nitpicks are trivial preference-based requests. These should be non-blocking by nature.  -->
**nitpick (non-blocking):** I know, I know

`/app/public/tmp` is there to work around the recent bug we have in ezMaster's instances, but hopefully we will solve it soon.

Plus, when you use `/tmp`, which is a mounted volume with ezMaster, the ops manage the files to delete them when too old. If you don't use `/tmp`, you have to manage that yourself, otherwise data filesystem will fill up quickly.‏

2024-03-21 10:59 UTC, parmentf commented on services/pdf-text/v1/pdf2txt.py
> +    pdf_filename = './tmp/'+name
<!-- Suggestions propose improvements to the current subject. It's important to be explicit and clear on what is being suggested and why it is an improvement. Consider using patches and the blocking or non-blocking decorations to further communicate your intent.  -->
**suggestion:** ‏Use a `TMP_DIR` constant

At least, you will be able to change it to `/tmp` quickly.

2024-03-21 10:59 UTC, parmentf commented on services/pdf-text/v1/pdf2txt.py
> +        os.remove(pdf_filename)
<!-- Questions are appropriate if you have a potential concern but are not quite sure if it's relevant or not. Asking the author for clarification or investigation can lead to a quick resolution.  -->
**question:** ‏Do you remove all tmp files?

It would be good. But not the best, since it's still in the container's filesystem.
I'm not sure that this union filsystem won't remember all deleted files.
That needs to be investigated.

2024-03-21 13:01 UTC, leogail commented on services/pdf-text/.dockerignore
> +!tmp
**suggestion (non-blocking):** 
```suggestion
```

2024-03-21 13:03 UTC, leogail commented on services/pdf-text/Dockerfile
> +RUN mkdir /app/public/tmp
**suggestion (if-minor):** 
```suggestion
```

2024-03-21 13:05 UTC, leogail commented on services/pdf-text/v1/pdf2txt.py
> +        os.remove(pdf_filename)
it seemed like yes but never seen when pgm crashes. Use /tmp instead (who's clean every weak) but we have to wait that the /tmp problem is resolved.

2024-04-09 12:21 UTC, parmentf requested changes

2024-04-09 12:21 UTC, parmentf commented on services/pdf-text/.dockerignore
> +!tmp
<!-- TODO's are small, trivial, but necessary changes. Distinguishing todo comments from issues: or suggestions: helps direct the reader's attention to comments requiring more involvement.  -->
**todo:** ‏Now that the /tmp bug is fixed, don't put temporary files in `/app/public`.
```suggestion
```

2024-04-09 12:21 UTC, parmentf commented on services/pdf-text/Dockerfile
> +USER daemon
<!-- Quibbles are very much like nitpick:, except it does not conjure up images of lice and animal hygiene practices.  -->
**quibble (non-blocking):** ‏No more useful

As the new [`docker-entrypoint.sh`](https://github.com/Inist-CNRS/web-services/blob/407a00e853601668cf0ee86b1f1480eca6dc262a/bases/ezs-python-server/docker-entrypoint.sh#L4-L5) changes `/app/public`'s owner.
```suggestion
```

2024-04-15 15:18 UTC, parmentf approved these changes

2024-04-17 06:49 UTC, merged

2024-04-17 07:01 UTC, parmentf commented on services/pdf-text/swagger.json
> +            "#DISABLED#x-profil": "Standard"
<!-- Nitpicks are trivial preference-based requests. These should be non-blocking by nature.  -->
**nitpick (non-blocking):** ‏`x-profil` should be enabled

Remove the `#DISABLED#` part of the field name.