Services/authors tools/migrate
Inist-CNRS/web-services pull request #63
Opened 2024-03-22 10:46 UTC by revolj

2024-03-22 11:03 UTC, parmentf reviewed
And of course: don't forget to add the other routes.

2024-03-22 11:03 UTC, parmentf commented on services/authors-tools/swagger.json
> +        "version": "0.0.0",
<!-- TODO's are small, trivial, but necessary changes. Distinguishing todo comments from issues: or suggestions: helps direct the reader's attention to comments requiring more involvement.  -->
**todo:** ‏Use the actual version of `authors-tools`
```suggestion
        "version": "2.4.0",
```

So that when you'll create a new version number, it will be higher than the old one.

2024-03-22 11:03 UTC, parmentf commented on services/authors-tools/v1/first-name/gender.ini
> +plugin = @ezs/analytics
<!-- Nitpicks are trivial preference-based requests. These should be non-blocking by nature.  -->
**nitpick (non-blocking):** ‏Remove `@ezs/analytics`, as we master the installed packages (via Dockerfile)
```suggestion
```

2024-04-23 13:30 UTC, parmentf requested changes

2024-04-23 13:30 UTC, parmentf commented on services/authors-tools/v1/corporate/private-public.py
> +    return
<!-- Questions are appropriate if you have a potential concern but are not quite sure if it's relevant or not. Asking the author for clarification or investigation can lead to a quick resolution.  -->
**question:** ‏Return nothing?

2024-04-23 13:30 UTC, parmentf commented on services/authors-tools/v1/corporate/private-public.py
> +    my_dict = read_json_file('./v1/corporate/abbreviations.json')
<!-- Polish comments are like a suggestion, where there is nothing necessarily wrong with the relevant content, there's just some ways to immediately improve the quality.  -->
**polish:** ‏Use a proper name
```suggestion
    abbreviations_dict = read_json_file('./v1/corporate/abbreviations.json')
```

Don't forget to refactor all usages of this variable!

2024-04-23 13:30 UTC, parmentf commented on services/authors-tools/v1/corporate/private-public.py
> +    for word in arr :
<!-- Suggestions propose improvements to the current subject. It's important to be explicit and clear on what is being suggested and why it is an improvement. Consider using patches and the blocking or non-blocking decorations to further communicate your intent.  -->
**suggestion:** ‏Better name
```suggestion
    affiliations = affiliation.split(" ")
    res = []
    for word in affiliations :
```

2024-04-23 13:30 UTC, parmentf commented on services/authors-tools/v1/corporate/private-public.py
> +        enterprise = adress[0]
```suggestion
        enterprise = name_enterprise(affiliation)
```

2024-04-25 14:51 UTC, revolj commented on services/authors-tools/v1/corporate/private-public.py
> +    return
`return None`. I specified

2024-04-25 14:52 UTC, revolj commented on services/authors-tools/package.json
> +    "scripts": {
Done.

2024-04-25 14:53 UTC, revolj commented on services/authors-tools/examples.http
> +]
Done.

2024-04-29 14:34 UTC, revolj commented
Problème lors de la création de la version.

2024-04-30 08:04 UTC, parmentf approved these changes

2024-06-24 07:53 UTC, parmentf commented
It seems that all is done for this service.
Only have to resolve conflicts in `README.md` and `package.json` before merging.

2024-06-24 09:08 UTC, merged