Update lda.ini
Inist-CNRS/web-services pull request #64
Opened 2024-03-25 09:52 UTC by leogail

Update doc of lda in swagger

2024-03-25 09:53 UTC, leogail commented on services/data-computer/v1/lda.ini
> +post.description = Crée à partir de l'ensemble des documents un champ `lda` constitué de plusieurs _topics_ eux-mêmes caractérisés par 10 mots.^M> **Note**: Le texte doit être en anglais.^M^M> **Note
**praise (non-blocking):** 
```suggestion
post.description = Créer à partir de l'ensemble des documents un champ `lda` constitué de plusieurs _topics_ eux-mêmes caractérisés par 10 mots.^M> **Note**: Le texte doit être en anglais.^M^M> **Note 2**: La qualité des résultats dépend du corpus et les _topics_ doivent être analysés par l'utilisateur avant d'être utilisés.
```

2024-04-08 15:38 UTC, parmentf requested changes

2024-04-08 15:38 UTC, parmentf commented on services/data-computer/v1/lda.ini
> +post.description = Créer à partir de l'ensemble des documents un champ `lda` constitué de plusieurs _topics_ eux-mêmes caractérisés par 10 mots.^M> **Note**: Le texte doit être en anglais.^M^M> **Not
<!-- Quibbles are very much like nitpick:, except it does not conjure up images of lice and animal hygiene practices.  -->
**quibble (non-blocking):** Let's be consistant

‏
```suggestion
post.description = Crée à partir de l'ensemble des documents un champ `lda` constitué de plusieurs _topics_ eux-mêmes caractérisés par 10 mots.^M> **Note**: Le texte doit être en anglais.^M^M> **Note 2**: La qualité des résultats dépend du corpus et les _topics_ doivent être analysés par l'utilisateur avant d'être utilisés.
```

2024-04-12 12:12 UTC, parmentf approved these changes

2024-04-12 12:13 UTC, merged