Services/biblio ref/process url pdf
Inist-CNRS/web-services pull request #73
Opened 2024-04-10 13:54 UTC by leogail

2024-04-12 07:08 UTC, parmentf requested changes

2024-04-12 07:08 UTC, parmentf commented on services/biblio-ref/v1/validate-pdf.py
> +        references_structured = [""]
<!-- Questions are appropriate if you have a potential concern but are not quite sure if it's relevant or not. Asking the author for clarification or investigation can lead to a quick resolution.  -->
**question:** ‏Why do you set one item in this list?

It should be the same with an empty list, shouldn't it?

2024-04-12 07:08 UTC, parmentf commented on services/biblio-ref/v1/validate-url.ini
> +post.responses.default.description = Le champ `value` est constitué d'un tableau constitués d'objets contenant les champs `doi`, `reference`, `url_pdf` et `status`.^M`status` prend plusieurs valeurs:
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** ‏
```suggestion
post.responses.default.description = Le champ `value` est un tableau d'objets contenant les champs `doi`, `reference`, `url_pdf` et `status`.^M`status` prend plusieurs valeurs:^M- `found`si la référence est trouvée et valide,^M- `not_found` si elle est hallucinée ou non présente dans Crossref,^M- `retracted` si elle est rétractée. Indique les erreurs possibles `error_service` ou `error_data`.
```

2024-04-12 07:08 UTC, parmentf commented on services/biblio-ref/v1/validate-url.ini
> +
<!-- TODO's are small, trivial, but necessary changes. Distinguishing todo comments from issues: or suggestions: helps direct the reader's attention to comments requiring more involvement.  -->
**todo:** ‏Add the example response.

2024-04-12 07:08 UTC, parmentf commented on services/biblio-ref/v1/validate-url.py
> +    name=str(round(random.random()*1000))+url.split('/')[-1]
<!-- Nitpicks are trivial preference-based requests. These should be non-blocking by nature.  -->
**nitpick (non-blocking):** Will 0-999 filenames always be enough?

I'd prefer you to also use the current time to differentiate filenames: you don't know, one day there perhaps several thousands of queries will happen in a second ;)‏

2024-04-12 07:08 UTC, parmentf commented on services/biblio-ref/v1/validate.py
> +    res = biblio_ref(ref_biblio)
<!-- Praises highlight something positive. Try to leave at least one of these comments per review. Do not leave false praise (which can actually be damaging). Do look for something to sincerely praise.  -->
**praise:** ‏Much simpler ! :+1:

2024-04-12 12:18 UTC, leogail commented on services/biblio-ref/v1/validate-url.py
> +    name=str(round(random.random()*1000))+url.split('/')[-1]
I hope so !

2024-04-12 12:23 UTC, leogail commented on services/biblio-ref/v1/validate-pdf.py
> +        references_structured = [""]
not exactly : with an empty list, the result is value : [ ] but not  with a single empty string element, [""].

BUT an empty list is a better output i guess : i'll change it !

2024-04-17 07:46 UTC, leogail commented on services/biblio-ref/examples.http
> +]
Done ! But not sure if i did good with tests.hurl file. Could you check it @parmentf ?

2024-04-17 11:31 UTC, leogail commented on services/biblio-ref/examples.http
> +]
nevermind ! file is ok this way

2024-04-29 09:28 UTC, parmentf requested changes

2024-04-30 09:38 UTC, leogail commented on services/biblio-ref/tests.hurl
> +variable "fr_computing_ref" exists
I understood what you are asking but i prefer do it with you for the first time

2024-05-24 06:54 UTC, parmentf approved these changes

2024-05-24 12:51 UTC, merged