add statistics entrypoint
Inist-CNRS/web-services pull request #75
Opened 2024-04-11 14:16 UTC by touv

2024-04-11 15:26 UTC, parmentf requested changes
**Warning**, [Dockerfile](https://github.com/Inist-CNRS/web-services/blob/services/data-computer/add-stats/services/data-computer/Dockerfile) in this branch is *not production-ready* (it does not yet use the last `ezs-python-server` and still have a `USER daemon` line).

The reason is, there is another PR that implements it, but is not yet merged: #64 
See its [Dockerfile](https://github.com/Inist-CNRS/web-services/blob/services/data-computer/doc-lda/services/data-computer/Dockerfile).

2024-04-11 15:26 UTC, parmentf commented on services/data-computer/v1/statistics.ini
> +post.description = Le corpus est analysé et pour chque valeur envoyée (champ value), le service retourne quelques statistiques.
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** Un tantinet de français + MarkDown‏
```suggestion
post.description = Le corpus est analysé et pour chaque valeur envoyée (champ `value`), le service retourne quelques statistiques.
```

2024-04-11 15:26 UTC, parmentf commented on services/data-computer/v1/statistics.ini
> +# Step 2 (générique): Traiter de manière asynchnore les items reçus
<!-- Polish comments are like a suggestion, where there is nothing necessarily wrong with the relevant content, there's just some ways to immediately improve the quality.  -->
**polish:** ‏Let's fix comments ;)
```suggestion
# Step 2 (générique): Traiter de manière asynchrone les items reçus
```

2024-04-11 15:26 UTC, parmentf commented on services/data-computer/v1/statistics.ini
> +# Step 2.0 (optionnel): Accélére le détachement du fork si l'enrichissement est lent
<!-- Polish comments are like a suggestion, where there is nothing necessarily wrong with the relevant content, there's just some ways to immediately improve the quality.  -->
**polish:** ‏Derechef
```suggestion
# Step 2.0 (optionnel): Accélère le détachement du fork si l'enrichissement est lent
```

2024-04-11 15:26 UTC, parmentf commented on services/data-computer/v1/statistics.ini
> +# Step 2.2 (générique): Enregister le résulat et signaler que le traitment est fini
<!-- Polish comments are like a suggestion, where there is nothing necessarily wrong with the relevant content, there's just some ways to immediately improve the quality.  -->
**polish:** ‏Fix comments
```suggestion
# Step 2.2 (générique): Enregistrer le résultat et signaler que le traitement est fini
```

2024-04-12 07:32 UTC, touv commented
> **Warning**, [Dockerfile](https://github.com/Inist-CNRS/web-services/blob/services/data-computer/add-stats/services/data-computer/Dockerfile) in this branch is _not production-ready_ (it does not yet use the last `ezs-python-server` and still has a `USER daemon` line).
> 
> The reason is, there is another PR that implements it, but is not yet merged: #64 See its [Dockerfile](https://github.com/Inist-CNRS/web-services/blob/services/data-computer/doc-lda/services/data-computer/Dockerfile). See #68

how to get out of this depthlock  ?

2024-04-12 09:05 UTC, parmentf commented
> > **Warning**, [Dockerfile](https://github.com/Inist-CNRS/web-services/blob/services/data-computer/add-stats/services/data-computer/Dockerfile) in this branch is _not production-ready_ (it does not yet use the last `ezs-python-server` and still has a `USER daemon` line).
> > The reason is, there is another PR that implements it, but is not yet merged: #64 See its [Dockerfile](https://github.com/Inist-CNRS/web-services/blob/services/data-computer/doc-lda/services/data-computer/Dockerfile). See #68
> 
> how to get out of this depthlock ?

I think we could improve the Docker in this PR.
It should be the same Dockerfile as in #64, and so no conflicts should arise.

2024-04-12 11:50 UTC, parmentf commented
It would be better with an example to test.

2024-04-12 11:57 UTC, touv commented
> It would be better with an example to test.

à mettre ici https://github.com/Inist-CNRS/web-services/blob/main/services/data-computer/tests.hurl#L40
;-)
I will do it asap

2024-04-15 14:57 UTC, parmentf requested changes

2024-04-15 14:57 UTC, parmentf commented on services/data-computer/tests.hurl
> +POST https://data-computer.services.istex.fr/v1/retrieve-json
<!-- Issues highlight specific problems with the subject under review. These problems can be user-facing or behind the scenes. It is strongly recommended to pair this comment with a suggestion. If you are not sure if a problem exists or not, consider leaving a question.  -->
**issue:** ‏You forgot the `host` variable
```suggestion
POST {{host}}/v1/retrieve-json
```

2024-04-16 07:00 UTC, parmentf commented
Ouch. The previous test fails now (tree-segment).

2024-04-17 14:32 UTC, merged