feat(astro-ner): migrate astro-ner
Inist-CNRS/web-services pull request #80
Opened 2024-04-18 13:42 UTC by revolj

2024-04-24 06:48 UTC, parmentf requested changes

2024-04-24 15:24 UTC, parmentf requested changes
Don't forget to create a new version (patch, except if you change anything in the behaviour of the service), to deploy the image in production, then to change the port in `swagger.json`, to activate the server, so that I can publish it.
Next we would be able to merge.

2024-04-24 15:24 UTC, parmentf commented on services/astro-ner/config.json
> +        "EZS_CONCURRENCY": 4,
<!-- Thoughts represent an idea that popped up from reviewing. These comments are non-blocking by nature, but they are extremely valuable and can lead to more focused initiatives and mentoring opportunities.  -->
**thought (non-blocking):** ‏Maybe we should not let concurrency to 4, as astro-ner uses a large model?

2024-04-24 15:24 UTC, parmentf commented on services/astro-ner/v1/find-astro.py
> +    SR = []
<!-- Quibbles are very much like nitpick:, except it does not conjure up images of lice and animal hygiene practices.  -->
**quibble (non-blocking):** ‏I don't find these variable names very meaningful.

2024-04-24 15:24 UTC, parmentf commented on services/astro-ner/v1/find-astro.py
> +        unidecode("Astèroïdes"): AST,
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** ‏
```suggestion
        unidecode("Astéroïdes"): AST,
```

2024-04-24 15:24 UTC, parmentf commented on services/astro-ner/v1/find-astro.py
> +        unidecode("Satue hypotétique"): ST,
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** ‏I'm not even sure of the meaning. Correct this if I'm wrong
```suggestion
        unidecode("Statut hypothétique"): ST,
```

2024-04-24 15:24 UTC, parmentf commented on services/astro-ner/v1/find-astro.py
> +        "sursaut radio, source radio, autres sursauts": SR,
<!-- Questions are appropriate if you have a potential concern but are not quite sure if it's relevant or not. Asking the author for clarification or investigation can lead to a quick resolution.  -->
**question:** ‏No more capitalization. Why?

2024-04-24 15:24 UTC, parmentf commented on services/astro-ner/v1/tagger.ini
> +
<!-- Polish comments are like a suggestion, where there is nothing necessarily wrong with the relevant content, there's just some ways to immediately improve the quality.  -->
**polish:** ‏It's a shame we don't have response for the examples.

2024-04-24 15:24 UTC, parmentf commented on services/astro-ner/package.json
> +    "version": "0.0.0",
<!-- TODO's are small, trivial, but necessary changes. Distinguishing todo comments from issues: or suggestions: helps direct the reader's attention to comments requiring more involvement.  -->
**todo:** Set the current version, so that next time we create a version, it is the good one.‏
```suggestion
    "version": "1.0.6",
```

2024-04-24 15:24 UTC, parmentf commented on services/astro-ner/swagger.json
> +        "version": "0.0.0",
<!-- TODO's are small, trivial, but necessary changes. Distinguishing todo comments from issues: or suggestions: helps direct the reader's attention to comments requiring more involvement.  -->
**todo:** ‏Set the current version
```suggestion
        "version": "1.0.6",
```

2024-04-25 09:12 UTC, revolj commented on services/astro-ner/v1/find-astro.py
> +    SR = []
I have to change the labels because they are too long.

2024-04-25 12:48 UTC, revolj commented on services/astro-ner/v1/tagger.ini
> +
Done

2024-04-25 13:06 UTC, revolj commented on services/astro-ner/config.json
> +        "EZS_CONCURRENCY": 4,
I can set to 1

2024-04-25 13:09 UTC, revolj commented on services/astro-ner/v1/find-astro.py
> +        "sursaut radio, source radio, autres sursauts": SR,
comes from the annotation file.

2024-05-02 13:32 UTC, leogail reviewed
I'll let François approve this but added some suggestions !

2024-05-02 13:32 UTC, leogail commented on services/astro-ner/v1/tagger.ini
> +size = 100
**suggestion (if-minor):** for refBib, this change was necessery. Maybe the VP will not crash anymore
```suggestion
size = 5
```

2024-05-02 13:32 UTC, leogail commented on services/astro-ner/v1/tagger.ini
> +size = 100
5 or 10 or ...

2024-05-02 13:32 UTC, leogail commented on services/astro-ner/config.json
> +        "EZS_VERBOSE": false,
**suggestion (non-blocking):** 
Since the service crashes the VP, setting verbose to true by default would allow users to see the logs without having to restart the enrichments.
```suggestion
        "EZS_VERBOSE": true,
```

2024-05-14 12:39 UTC, parmentf commented on services/astro-ner/v1/tagger.ini
> +size = 100
Right, it has to be adapted to the capacity of the program called: it is the size of the batch sent to the program at once (the number of lines the program will receive at most).

2024-05-14 12:42 UTC, parmentf commented
<!-- Notes are always non-blocking and simply highlight something the reader should take note of.  -->
**note (non-blocking):** The team members have the right to approve a PR (via a code review).

You don't have to wait for me, unless you are not sure of yourselves.‏

2024-05-29 07:05 UTC, parmentf approved these changes

2024-05-29 07:08 UTC, leogail commented on services/astro-ner/Dockerfile
> +RUN pip install torch==1.10.2+cpu torchvision==0.11.3+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html
**question (non-blocking):** is `torchvision` a flair dependency ?

2024-05-29 13:20 UTC, parmentf requested changes

2024-05-29 13:20 UTC, parmentf commented on services/astro-ner/Dockerfile
> +RUN pip install torch==1.10.2+cpu torchvision==0.11.3+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html
Good question. Has to be tested.

2024-06-14 12:45 UTC, parmentf commented
Maybe this service could use [ezs-python-pytorch-server](https://github.com/Inist-CNRS/web-services/tree/main/bases/ezs-python-pytorch-server)?

2024-06-18 13:27 UTC, merged