Services/text clustering/split service
Inist-CNRS/web-services pull request #85
Opened 2024-05-27 11:10 UTC by leogail

split "data-computer services" and clustering service (too large)

2024-05-27 11:11 UTC, leogail commented
@parmentf : i'll need some helps i guess to generate test.hurl for clustering

2024-06-04 13:28 UTC, parmentf commented on services/text-clustering/Dockerfile
> +    "@ezs/spawn@1.4.5"
<!-- Quibbles are very much like nitpick:, except it does not conjure up images of lice and animal hygiene practices.  -->
**quibble (non-blocking):** ‏Better use last versions
```suggestion
    "@ezs/analytics@2.3.2" \
    "@ezs/basics@2.6.1" \
    "@ezs/core@3.9.0" \
    "@ezs/spawn@1.4.6"
```

2024-06-04 13:28 UTC, parmentf commented on services/text-clustering/README.md
> +Créer plusieurs groupe afin d'y classifier les différents textes en fonction de leur similarité.^M> - Le nombre de `cluster` est déterminé de manière automatique et des documents peuvent être considé
<!-- Polish comments are like a suggestion, where there is nothing necessarily wrong with the relevant content, there's just some ways to immediately improve the quality.  -->
**polish:** ‏Would be clearer without `^M`
```suggestion
Créer plusieurs groupes afin d'y classifier les différents textes en fonction de leur similarité.

> - Le nombre de `cluster` est déterminé de manière automatique et des documents peuvent être considérés comme du bruit (dans ce cas précis, le label de leur cluster sera `0` ; les documents appartenant au cluster 0 ne sont pas regroupés).
> - L'entrée peut être un texte court (type titre ou petit abstract), mais aussi une liste de mots-clés.
```

The `insert:description` script will replace all `\n` with `^M`.

2024-06-04 13:28 UTC, parmentf commented on services/text-clustering/config.json
> +        "EZS_DESCRIPTION": "Créer plusieurs groupe afin d'y classifier les différents textes en fonction de leur similarité.^M> - Le nombre de `cluster` est déterminé de manière automatique et des do
<!-- Polish comments are like a suggestion, where there is nothing necessarily wrong with the relevant content, there's just some ways to immediately improve the quality.  -->
**polish:** Here, you can replace `^M` with `\n`, it's JSON‏
```suggestion
        "EZS_DESCRIPTION": "Créer plusieurs groupes afin d'y classifier les différents textes en fonction de leur similarité.\n\n> - Le nombre de `cluster` est déterminé de manière automatique et des documents peuvent être considérés comme du bruit (dans ce cas précis, le label de leur cluster sera `0` ; les documents appartenant au cluster 0 ne sont pas regroupés).\n> - L'entrée peut être un texte court (type titre ou petit abstract), mais aussi une liste de mots-clés.",
```
This will be description part of the server in `swagger.json` of https://text-clustering.services.istex.fr

2024-06-04 13:28 UTC, parmentf commented on services/text-clustering/README.md
> +Créer différents `clusters` à partir d'un ensemble de textes courts ou d'un ensemble de listes de mots-clés.
<!-- Suggestions propose improvements to the current subject. It's important to be explicit and clear on what is being suggested and why it is an improvement. Consider using patches and the blocking or non-blocking decorations to further communicate your intent.  -->
**suggestion:** ‏Say that here is an asynchronous web service (not same usage as classical web services)

2024-06-04 13:28 UTC, parmentf commented on services/text-clustering/swagger.json
> +        "description": "Créer plusieurs groupe afin d'y classifier les différents textes en fonction de leur similarité. Le nombre de clusters est déterminé de manière automatique et des documents pe
<!-- Questions are appropriate if you have a potential concern but are not quite sure if it's relevant or not. Asking the author for clarification or investigation can lead to a quick resolution.  -->
**question:** I wonder what is used, whether this description or the content of `EZS_DESCRIPTION` :thinking: ‏

I think it's `EZS_DESCRIPTION`.

Sources:
- https://github.com/Inist-CNRS/ezs/blob/b4c9df4c59ed90a4a0ad6d6c8baf04fb1b3e20b3/packages/core/src/server/serverInformation.js#L62
- https://github.com/Inist-CNRS/ezs/blob/b4c9df4c59ed90a4a0ad6d6c8baf04fb1b3e20b3/packages/core/src/settings.js#L44

2024-06-04 13:28 UTC, parmentf commented on services/text-clustering/tests.hurl
> +variable "computing_token" exists
<!-- Suggestions propose improvements to the current subject. It's important to be explicit and clear on what is being suggested and why it is an improvement. Consider using patches and the blocking or non-blocking decorations to further communicate your intent.  -->
**suggestion:** Take example on `data-computer` to add the next steps

You have to evaluate the minimum time to treat the example.

https://github.com/Inist-CNRS/web-services/blob/main/services/data-computer/tests.hurl#L25-L28‏

2024-06-04 13:33 UTC, parmentf commented on services/text-clustering/swagger.json
> +        "description": "Créer plusieurs groupe afin d'y classifier les différents textes en fonction de leur similarité. Le nombre de clusters est déterminé de manière automatique et des documents pe
Nope, it's `description` from the `swagger.json`, which can be generated from `swagger.md` using [insert:swagger:description](https://github.com/Inist-CNRS/web-services/blob/main/SCRIPTS.md#insertswaggerdescription).

2024-06-18 07:56 UTC, leogail commented on services/text-clustering/README.md
> +Créer différents `clusters` à partir d'un ensemble de textes courts ou d'un ensemble de listes de mots-clés.
**praise:** 
```suggestion
Créer différents `clusters` à partir d'un ensemble de textes courts ou d'un ensemble de listes de mots-clés. Ce web service est asynchrone et traite des corpus et non des documents.
```

2024-06-21 13:46 UTC, parmentf requested changes

2024-06-21 13:46 UTC, parmentf commented on services/text-clustering/Dockerfile
> +    "@ezs/spawn@1.4.6"
<!-- Thoughts represent an idea that popped up from reviewing. These comments are non-blocking by nature, but they are extremely valuable and can lead to more focused initiatives and mentoring opportunities.  -->
**thought (non-blocking):** ‏Here should add only packages not already installed in the base image [ezs-python-server](https://github.com/Inist-CNRS/web-services/blob/ea5fb2e0aced7e1470a93203806f011d2c6f2543/bases/ezs-python-server/Dockerfile#L12-L15)

That way, when we update the base image, we can just change the version on line 19, and boom, updated image.

```suggestion
```

2024-06-21 13:46 UTC, parmentf commented on services/text-clustering/Dockerfile
> +ENV NUMBA_CACHE_DIR=/tmp/numba_cache
<!-- Thoughts represent an idea that popped up from reviewing. These comments are non-blocking by nature, but they are extremely valuable and can lead to more focused initiatives and mentoring opportunities.  -->
**thought (non-blocking):** ‏Not sure the `NUMBA_CACHE_DIR` variable will be available in the server's environment (the one of `daemon` user), as we are in user `root`'s environment.

Maybe it would be better to put it in `config.json`, as the variables are instanciated in the right environment?
:thinking:

2024-06-21 13:46 UTC, parmentf commented on services/text-clustering/README.md
> +Créer plusieurs groupes afin d'y classifier les différents textes en fonction de leur similarité.
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** ‏
```suggestion
Crée différents `clusters` à partir d'un ensemble de textes courts ou d'un ensemble de listes de mots-clés. Ce web service est asynchrone et traite des corpus et non des documents.

Crée plusieurs groupes afin d'y classifier les différents textes en fonction de leur similarité.
```

2024-06-21 13:46 UTC, parmentf commented on services/text-clustering/config.json
> +        "EZS_DESCRIPTION": "Créer plusieurs groupes afin d'y classifier les différents textes en fonction de leur similarité.\n\n> - Le nombre de `cluster` est déterminé de manière automatique et des
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** ‏
```suggestion
        "EZS_TITLE": "Crée différents `clusters` à partir d'un ensemble de textes courts ou d'un ensemble de listes de mots-clés.",
        "EZS_DESCRIPTION": "Crée plusieurs groupes afin d'y classifier les différents textes en fonction de leur similarité.\n\n> - Le nombre de `cluster` est déterminé de manière automatique et des documents peuvent être considérés comme du bruit (dans ce cas précis, le label de leur cluster sera `0` ; les documents appartenant au cluster 0 ne sont pas regroupés).\n> - L'entrée peut être un texte court (type titre ou petit abstract), mais aussi une liste de mots-clés.",
```

2024-06-21 13:46 UTC, parmentf commented on services/text-clustering/swagger.json
> +        "description": "Créer plusieurs groupe afin d'y classifier les différents textes en fonction de leur similarité. Le nombre de clusters est déterminé de manière automatique et des documents pe
<!-- Typo comments are like todo:, where the main issue is a mispelling.  -->
**typo:** ‏
```suggestion
        "title": "text-clustering - Crée différents clusters à partir d'un ensemble de textes courts ou d'un ensemble de listes de mots-clés.",
        "description": "Crée plusieurs groupe afin d'y classifier les différents textes en fonction de leur similarité. Le nombre de clusters est déterminé de manière automatique et des documents peuvent être considérés comme du bruit (dans ce cas précis, le label de leur cluster sera 0 ; les documents appartenant au cluster 0 ne sont pas regroupés ensembles). L'entrée peut être un texte court (type titre ou petit abstract), mais aussi une liste de mots-clés.",
```

2024-06-24 12:52 UTC, leogail commented on services/text-clustering/Dockerfile
> +ENV NUMBA_CACHE_DIR=/tmp/numba_cache
Looks like put it here worked. I don't understand why. Maybe it is usefull only during installation ?

2024-06-24 14:09 UTC, parmentf commented on services/text-clustering/swagger.json
> +            "url": "http://vptdmjobs.intra.inist.fr:49172/",
<!-- Questions are appropriate if you have a potential concern but are not quite sure if it's relevant or not. Asking the author for clarification or investigation can lead to a quick resolution.  -->
**question:** ‏Isn't it 49177?

2024-06-24 14:09 UTC, parmentf commented on services/text-clustering/v1/clustering.py
> +# from prometheus_client import CollectorRegistry, Counter, push_to_gateway
<!-- Suggestions propose improvements to the current subject. It's important to be explicit and clear on what is being suggested and why it is an improvement. Consider using patches and the blocking or non-blocking decorations to further communicate your intent.  -->
**suggestion:** ‏We should use an environment variable to know if we are in production or not (`NODE_ENV` ?)

2024-06-26 07:57 UTC, parmentf commented on services/text-clustering/Dockerfile
> +ENV NUMBA_CACHE_DIR=/tmp/numba_cache
OK. :crossed_fingers:

2024-06-26 07:58 UTC, parmentf commented
OK, it seems that 15 seconds is not enough on GitHub. Let's try 30 seconds?

2024-06-26 09:50 UTC, leogail commented
> OK, it seems that 15 seconds is not enough on GitHub. Let's try 30 seconds?

okkkk let's go

2024-07-22 12:40 UTC, parmentf commented
Maybe it would be clearer to name the service `data-clustering`, to show that it's an asynchronous service?

2024-07-22 13:05 UTC, parmentf requested changes
We have to forge a way to use `NODE_ENV` to avoid tests on GitHub to try to connect to a non-public server...

2024-07-22 13:05 UTC, parmentf commented on services/text-clustering/v1/noise.py
> +    sys.stdout.write(json.dumps({"value":"No noise in your datas"}))
<!-- Thoughts represent an idea that popped up from reviewing. These comments are non-blocking by nature, but they are extremely valuable and can lead to more focused initiatives and mentoring opportunities.  -->
**thought (non-blocking):** ‏What a difficult case!
I would have said that the response for a non-noisy corpus would have been an empty array.
BUT if the output is in JSONLines, that would mean no output at all, and finally, an empty response instead of a response containing an empty array :thinking:

2024-07-31 08:50 UTC, leogail commented on services/text-clustering/v1/noise.py
> +    sys.stdout.write(json.dumps({"value":"No noise in your datas"}))
changed it

2024-08-01 13:43 UTC, parmentf approved these changes

2024-08-01 14:37 UTC, merged