[diseases-ner] now using the torch base image
Inist-CNRS/web-services pull request #91
Opened 2024-06-05 12:39 UTC by AlasDiablo

2024-06-05 12:44 UTC, parmentf requested changes

2024-06-05 13:13 UTC, leogail approved these changes

2024-06-05 13:13 UTC, leogail commented on services/diseases-ner/Dockerfile
> +FROM python:3.9-slim-bullseye as dvc-files
**praise:** Good idea

2024-06-06 06:50 UTC, parmentf approved these changes

2024-06-21 07:54 UTC, parmentf requested changes

2024-06-21 07:54 UTC, parmentf commented on services/diseases-ner/Dockerfile
> +FROM cnrsinist/ezs-python-pytorch-server:py3.9-no16-1.1.1
<!-- Suggestions propose improvements to the current subject. It's important to be explicit and clear on what is being suggested and why it is an improvement. Consider using patches and the blocking or non-blocking decorations to further communicate your intent.  -->
**suggestion:** ‏Use the last version: 1.1.2
```suggestion
FROM cnrsinist/ezs-python-pytorch-server:py3.9-no16-1.1.2
```

2024-06-21 12:23 UTC, parmentf approved these changes

2024-06-21 12:26 UTC, parmentf commented
Please create a version (patch), that I can deploy. Then, I'll modify `swagger.json` and merge.

2024-06-21 13:23 UTC, merged